galaxy_info:
  author: Kevin Harvey
  description: NGINX HTTP/3 Web Server Deployment
 
  license: GPLv3

  min_ansible_version: "2.1"

  platforms:
    - name: EL
      versions:
      - "9"
 
  galaxy_tags: []

dependencies: []