---
- name: Set SELinux Targeted Enforcing
  ansible.posix.selinux:
    policy: targeted
    state: enforcing
  when: enable_selinux == true

- name: Set SELinux Enforcing - Configuration
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=enforcing'
    state: present
  when: enable_selinux == true

- name: Set SELinux Targeted Permissive
  ansible.posix.selinux:
    policy: targeted
    state: permissive
  when: enable_selinux == false

- name: Set SELinux Permissive - Configuration
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=permissive'
    state: present
  when: enable_selinux == false

- name: Install Common Packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ common_packages }}"

- name: Copy Message of the Day (/etc/motd)
  ansible.builtin.template:
    src: templates/motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644
    backup: false

- name: Copy Pre-Authentication Banner (/etc/banner)
  ansible.builtin.template:
    src: templates/banner.j2
    dest: /etc/banner
    owner: root
    group: root
    mode: 0644
    backup: false

- name: Append SSHD Configuration - Banner
  ansible.builtin.template:
    src: templates/sshd_banner_config.j2
    dest: /etc/ssh/sshd_config.d/sshd_banner.conf
    owner: root
    group: root
    mode: 0600
    backup: false
  notify: Restart SSHD

- name: Append SSHD Configuration - Disable Password Authentication
  ansible.builtin.template:
    src: templates/sshd_auth_config.j2
    dest: /etc/ssh/sshd_config.d/sshd_password_auth.conf
    owner: root
    group: root
    mode: 0600
    backup: false
  notify: Restart SSHD

- name: Install QEMU Guest Agent
  ansible.builtin.package:
    name: qemu-guest-agent
    state: present
  when: qemu_agent == true