/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/__root"
import { Route as AboutRouteImport } from "./app/about"
import { Route as IndexRouteImport } from "./app/index"
import { Route as NewIndexRouteImport } from "./app/new/index"
import { Route as InventoryIndexRouteImport } from "./app/inventory/index"
import { Route as NewNamespaceRouteImport } from "./app/new/namespace"
import { Route as NewVmIndexRouteImport } from "./app/new/vm/index"

const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const NewIndexRoute = NewIndexRouteImport.update({
  id: "/new/",
  path: "/new/",
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: "/inventory/",
  path: "/inventory/",
  getParentRoute: () => rootRouteImport,
} as any)
const NewNamespaceRoute = NewNamespaceRouteImport.update({
  id: "/new/namespace",
  path: "/new/namespace",
  getParentRoute: () => rootRouteImport,
} as any)
const NewVmIndexRoute = NewVmIndexRouteImport.update({
  id: "/new/vm/",
  path: "/new/vm/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/new/namespace": typeof NewNamespaceRoute
  "/inventory/": typeof InventoryIndexRoute
  "/new/": typeof NewIndexRoute
  "/new/vm/": typeof NewVmIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/new/namespace": typeof NewNamespaceRoute
  "/inventory": typeof InventoryIndexRoute
  "/new": typeof NewIndexRoute
  "/new/vm": typeof NewVmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/new/namespace": typeof NewNamespaceRoute
  "/inventory/": typeof InventoryIndexRoute
  "/new/": typeof NewIndexRoute
  "/new/vm/": typeof NewVmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/about"
    | "/new/namespace"
    | "/inventory/"
    | "/new/"
    | "/new/vm/"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/about" | "/new/namespace" | "/inventory" | "/new" | "/new/vm"
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/new/namespace"
    | "/inventory/"
    | "/new/"
    | "/new/vm/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  NewNamespaceRoute: typeof NewNamespaceRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  NewIndexRoute: typeof NewIndexRoute
  NewVmIndexRoute: typeof NewVmIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/about": {
      id: "/about"
      path: "/about"
      fullPath: "/about"
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/new/": {
      id: "/new/"
      path: "/new"
      fullPath: "/new/"
      preLoaderRoute: typeof NewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/inventory/": {
      id: "/inventory/"
      path: "/inventory"
      fullPath: "/inventory/"
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/new/namespace": {
      id: "/new/namespace"
      path: "/new/namespace"
      fullPath: "/new/namespace"
      preLoaderRoute: typeof NewNamespaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/new/vm/": {
      id: "/new/vm/"
      path: "/new/vm"
      fullPath: "/new/vm/"
      preLoaderRoute: typeof NewVmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  NewNamespaceRoute: NewNamespaceRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  NewIndexRoute: NewIndexRoute,
  NewVmIndexRoute: NewVmIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
